### ISSUE TITLE
Improve Rust implementation

### ISSUE THREAD

**Issue by kawogi** [FredySandoval/benchmark-indexof#1]
The Rust implementation doesn't stop on the first match but continues to the end of the file. Also the `window` method is a very slow approach (see comments here https://stackoverflow.com/questions/35901547/how-can-i-find-a-subsequence-in-a-u8-slice )

I suggest this implementation which tripled the performance for me (YMMV because you used a different binary file)

```toml
[dependencies]
memmem = "0.1.1"
```

```rust
#![warn(clippy::pedantic)]
use std::{
    fs::File,
    io::{self, Seek, Read},
};

use memmem::{TwoWaySearcher, Searcher};

const CAP: usize = 65536;
const NEEDLE: [u8; 12] = *b"--boundary--";

fn main() -> io::Result<()> {
    let mut file = File::open("/home/kai/temp/file.bin")?;
    let mut count = 0;
    let searcher = TwoWaySearcher::new(&NEEDLE);
    let mut buffer = vec![0; CAP];

    loop {
        count += 1;
        match file.read(&mut buffer)? {
            0 => break,
            length => {
                if let Some(offset) = searcher.search_in(&buffer[0..length]) {
                    println!("Number of chunks {:?}", count);
                    println!("Found index {:?}.", file.stream_position().unwrap() - length as u64 + offset as u64);
                    return Ok(());
                }
            }
        };
    }

    Ok(())
}
```

I didn't fix the bug where needles that lie across a chunk boundary won't be found.

I'd love to see your numbers updated with that approach.

**Comment by FredySandoval** [comment]
Indeed your implementation of Rust is faster, I will add the code and update results. Thanks for taking the time. 🙂

**Comment by FredySandoval** [comment]
![results1](https://user-images.githubusercontent.com/45242501/179337732-c83c5686-09e7-4a88-9f8c-eb9896560c1d.png)

will update soon, thanks

**Comment by kawogi** [comment]
Awesome! Thanks for the quick update.
That's looks more like what I expected ;)
